version: '3'

services:
   ml:
     environment:
       - PORT=9000
       - WSS_PORT=9000
     build: .
     volumes:
       - .:/media
     ports:
       - "9000:9000"
     restart: always

   frontend:
     build: frontend
     ports:
       - "8081:8081"
     restart: always
